import { QueryInterface } from 'sequelize';

export default {
  up: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkInsert(
      'drinks',
      [
        {
          'idDrink': 1,
          'strDrink': 'GG',
          'strDrinkAlternate': null,
          'strTags': null,
          'strCategory': 'Ordinary Drink',
          'strAlcoholic': 'Optional alcohol',
          'strInstructions': 'Pour the Galliano liqueur over ice. Fill the remainder of the glass with ginger ale and thats all there is to it. You now have a your very own GG.',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg',
          'strIngredient1': 'Galliano',
          'strIngredient2': 'Ginger ale',
          'strIngredient3': 'Ice',
          'strIngredient4': null,
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '2 1/2 shots ',
          'strMeasure2': null,
          'strMeasure3': null,
          'strMeasure4': null,
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2016-07-18 22:06:00'
        },
        {
          'idDrink': 2,
          'strDrink': 'A1',
          'strDrinkAlternate': null,
          'strTags': null,
          'strCategory': 'Cocktail',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': 'Pour all ingredients into a cocktail shaker, mix and serve over ice into a chilled glass.',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg',
          'strIngredient1': 'Gin',
          'strIngredient2': 'Grand Marnier',
          'strIngredient3': 'Lemon Juice',
          'strIngredient4': 'Grenadine',
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '1 3/4 shot ',
          'strMeasure2': '1 Shot ',
          'strMeasure3': '1/4 Shot',
          'strMeasure4': '1/8 Shot',
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2017-09-07 21:42:09'
        },
        {
          'idDrink': 3,
          'strDrink': 'ABC',
          'strDrinkAlternate': null,
          'strTags': null,
          'strCategory': 'Shot',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': 'Layered in a shot glass.',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/tqpvqp1472668328.jpg',
          'strIngredient1': 'Amaretto',
          'strIngredient2': 'Baileys irish cream',
          'strIngredient3': 'Cognac',
          'strIngredient4': null,
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '1/3 ',
          'strMeasure2': '1/3 ',
          'strMeasure3': '1/3 ',
          'strMeasure4': null,
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2016-08-31 19:32:08'
        },
        {
          'idDrink': 4,
          'strDrink': 'Kir',
          'strDrinkAlternate': null,
          'strTags': 'IBA,ContemporaryClassic',
          'strCategory': 'Ordinary Drink',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': 'Add the crème de cassis to the bottom of the glass, then top up with wine.',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/apneom1504370294.jpg',
          'strIngredient1': 'Creme de Cassis',
          'strIngredient2': 'Champagne',
          'strIngredient3': null,
          'strIngredient4': null,
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '1 part ',
          'strMeasure2': '5 parts ',
          'strMeasure3': null,
          'strMeasure4': null,
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2017-09-02 17:38:14'
        },
        {
          'idDrink': 5,
          'strDrink': '747',
          'strDrinkAlternate': null,
          'strTags': null,
          'strCategory': 'Shot',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': 'pour kaluha, then Baileys, then Frangelico not chilled and not layered -- SERVE!!!',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/xxsxqy1472668106.jpg',
          'strIngredient1': 'Kahlua',
          'strIngredient2': 'Baileys irish cream',
          'strIngredient3': 'Frangelico',
          'strIngredient4': null,
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '1/3 part ',
          'strMeasure2': '1/3 part ',
          'strMeasure3': '1/3 part ',
          'strMeasure4': null,
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2016-08-31 19:28:26'
        },
        {
          'idDrink': 6,
          'strDrink': '252',
          'strDrinkAlternate': null,
          'strTags': null,
          'strCategory': 'Shot',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': 'Add both ingredients to shot glass, shoot, and get drunk quick',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rtpxqw1468877562.jpg',
          'strIngredient1': '151 proof rum',
          'strIngredient2': 'Wild Turkey',
          'strIngredient3': null,
          'strIngredient4': null,
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '1/2 shot Bacardi ',
          'strMeasure2': '1/2 shot ',
          'strMeasure3': null,
          'strMeasure4': null,
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2016-07-18 22:32:42'
        },
        {
          'idDrink': 7,
          'strDrink': 'Ace',
          'strDrinkAlternate': null,
          'strTags': null,
          'strCategory': 'Cocktail',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': 'Shake all the ingredients in a cocktail shaker and ice then strain in a cold glass.',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/l3cd7f1504818306.jpg',
          'strIngredient1': 'Gin',
          'strIngredient2': 'Grenadine',
          'strIngredient3': 'Heavy cream',
          'strIngredient4': 'Milk',
          'strIngredient5': 'Egg White',
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '2 shots ',
          'strMeasure2': '1/2 shot ',
          'strMeasure3': '1/2 shot ',
          'strMeasure4': '1/2 shot',
          'strMeasure5': '1/2 Fresh',
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2017-09-07 22:05:06'
        },
        {
          'idDrink': 8,
          'strDrink': 'Adam',
          'strDrinkAlternate': null,
          'strTags': 'Alcoholic,Holiday',
          'strCategory': 'Ordinary Drink',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': 'In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a cocktail glass.',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/v0at4i1582478473.jpg',
          'strIngredient1': 'Dark rum',
          'strIngredient2': 'Lemon juice',
          'strIngredient3': 'Grenadine',
          'strIngredient4': null,
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '2 oz ',
          'strMeasure2': '1 oz ',
          'strMeasure3': '1 tsp ',
          'strMeasure4': null,
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2016-09-02 11:29:29'
        },
        {
          'idDrink': 9,
          'strDrink': 'B-53',
          'strDrinkAlternate': null,
          'strTags': null,
          'strCategory': 'Shot',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': 'Layer the Kahlua, Sambucca and Grand Marnier into a shot glas in that order. Better than B-52',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rwqxrv1461866023.jpg',
          'strIngredient1': 'Kahlua',
          'strIngredient2': 'Sambuca',
          'strIngredient3': 'Grand Marnier',
          'strIngredient4': null,
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '1/3 shot ',
          'strMeasure2': '1/3 shot ',
          'strMeasure3': '1/3 shot ',
          'strMeasure4': null,
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2016-04-28 18:53:43'
        },
        {
          'idDrink': 10,
          'strDrink': 'AT&T',
          'strDrinkAlternate': null,
          'strTags': null,
          'strCategory': 'Ordinary Drink',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': 'Pour Vodka and Gin over ice, add Tonic and Stir',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rhhwmp1493067619.jpg',
          'strIngredient1': 'Absolut Vodka',
          'strIngredient2': 'Gin',
          'strIngredient3': 'Tonic water',
          'strIngredient4': null,
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '1 oz ',
          'strMeasure2': '1 oz ',
          'strMeasure3': '4 oz ',
          'strMeasure4': null,
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2017-04-24 22:00:19'
        },
        {
          'idDrink': 11,
          'strDrink': 'ACID',
          'strDrinkAlternate': null,
          'strTags': null,
          'strCategory': 'Shot',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': 'Poor in the 151 first followed by the 101 served with a Coke or Dr Pepper chaser.',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/xuxpxt1479209317.jpg',
          'strIngredient1': '151 proof rum',
          'strIngredient2': 'Wild Turkey',
          'strIngredient3': null,
          'strIngredient4': null,
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '1 oz Bacardi ',
          'strMeasure2': '1 oz ',
          'strMeasure3': null,
          'strMeasure4': null,
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2016-11-15 11:28:37'
        },
        {
          'idDrink': 12,
          'strDrink': 'B-52',
          'strDrinkAlternate': null,
          'strTags': 'IBA,NewEra',
          'strCategory': 'Shot',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': 'Layer ingredients into a shot glass. Serve with a stirrer.',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/5a3vg61504372070.jpg',
          'strIngredient1': 'Baileys irish cream',
          'strIngredient2': 'Grand Marnier',
          'strIngredient3': 'Kahlua',
          'strIngredient4': null,
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '1/3 ',
          'strMeasure2': '1/3 ',
          'strMeasure3': '1/4 ',
          'strMeasure4': null,
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2017-09-02 18:07:51'
        },
        {
          'idDrink': 13,
          'strDrink': 'H.D.',
          'strDrinkAlternate': null,
          'strTags': null,
          'strCategory': 'Coffee / Tea',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': 'Mix the whisky and Baileys Cream in a beer-glass (at least 50 cl). Fill the rest of the glass with coffee.',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/upusyu1472667977.jpg',
          'strIngredient1': 'Whisky',
          'strIngredient2': 'Baileys irish cream',
          'strIngredient3': 'Coffee',
          'strIngredient4': null,
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '4 cl ',
          'strMeasure2': '8 cl ',
          'strMeasure3': null,
          'strMeasure4': null,
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2016-08-31 19:26:18'
        },
        {
          'idDrink': 14,
          'strDrink': 'Smut',
          'strDrinkAlternate': null,
          'strTags': null,
          'strCategory': 'Punch / Party Drink',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': 'Throw it all together and serve real cold.',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rx8k8e1504365812.jpg',
          'strIngredient1': 'Red wine',
          'strIngredient2': 'Peach schnapps',
          'strIngredient3': 'Pepsi Cola',
          'strIngredient4': 'Orange juice',
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '1/3 part ',
          'strMeasure2': '1 shot ',
          'strMeasure3': '1/3 part ',
          'strMeasure4': '1/3 part ',
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2017-09-02 16:23:32'
        },
        {
          'idDrink': 15,
          'strDrink': 'Rose',
          'strDrinkAlternate': null,
          'strTags': 'IBA,ContemporaryClassic',
          'strCategory': 'Ordinary Drink',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': 'Shake together in a cocktail shaker, then strain into chilled glass. Garnish and serve.',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/8kxbvq1504371462.jpg',
          'strIngredient1': 'Dry Vermouth',
          'strIngredient2': 'Gin',
          'strIngredient3': 'Apricot brandy',
          'strIngredient4': 'Lemon juice',
          'strIngredient5': 'Grenadine',
          'strIngredient6': 'Powdered sugar',
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '1/2 oz ',
          'strMeasure2': '1 oz ',
          'strMeasure3': '1/2 oz ',
          'strMeasure4': '1/2 tsp ',
          'strMeasure5': '1 tsp ',
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2017-09-02 17:57:42'
        },
        {
          'idDrink': 16,
          'strDrink': 'A. J.',
          'strDrinkAlternate': null,
          'strTags': null,
          'strCategory': 'Ordinary Drink',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': 'Shake ingredients with ice, strain into a cocktail glass, and serve.',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/l74qo91582480316.jpg',
          'strIngredient1': 'Applejack',
          'strIngredient2': 'Grapefruit juice',
          'strIngredient3': null,
          'strIngredient4': null,
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '1 1/2 oz ',
          'strMeasure2': '1 oz ',
          'strMeasure3': null,
          'strMeasure4': null,
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2016-09-02 11:16:58'
        },
        {
          'idDrink': 17,
          'strDrink': 'Derby',
          'strDrinkAlternate': null,
          'strTags': 'Classic,IBA',
          'strCategory': 'Ordinary Drink',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': 'Pour all ingredients into a mixing glass with ice. Stir. Strain into a cocktail glass. Garnish with a sprig of fresh mint in the drink.',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/i502ra1504349156.jpg',
          'strIngredient1': 'gin',
          'strIngredient2': 'Peach Bitters',
          'strIngredient3': 'Mint',
          'strIngredient4': null,
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '6 cl',
          'strMeasure2': '2 dashes',
          'strMeasure3': '2 Fresh leaves',
          'strMeasure4': null,
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2017-09-02 11:45:56'
        },
        {
          'idDrink': 18,
          'strDrink': 'Karsk',
          'strDrinkAlternate': null,
          'strTags': null,
          'strCategory': 'Ordinary Drink',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': 'Put a copper coin in a coffe-cup and fill up with coffee until you no longer see the coin, then add alcohol until you see the coin. Norwegian speciality.',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/808mxk1487602471.jpg',
          'strIngredient1': 'Coffee',
          'strIngredient2': 'Grain alcohol',
          'strIngredient3': null,
          'strIngredient4': null,
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '1 part ',
          'strMeasure2': '2 parts ',
          'strMeasure3': null,
          'strMeasure4': null,
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2017-02-20 14:54:31'
        },
        {
          'idDrink': 19,
          'strDrink': 'Melya',
          'strDrinkAlternate': null,
          'strTags': null,
          'strCategory': 'Coffee / Tea',
          'strAlcoholic': 'Non alcoholic',
          'strInstructions': 'Brew espresso. In a coffee mug, place 1 teaspoon of unsweetened powdered cocoa, then cover a teaspoon with honey and drizzle it into the cup. Stir while the coffee brews, this is the fun part. The cocoa seems to coat the honey without mixing, so you get a dusty, sticky mass that looks as though it will never mix. Then all at once, presto! It looks like dark chocolate sauce. Pour hot espresso over the honey, stirring to dissolve. Serve with cream.',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/xwtptq1441247579.jpg',
          'strIngredient1': 'Espresso',
          'strIngredient2': 'Honey',
          'strIngredient3': 'Cocoa powder',
          'strIngredient4': null,
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': null,
          'strMeasure2': 'Unsweetened ',
          'strMeasure3': null,
          'strMeasure4': null,
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2015-09-03 03:32:59'
        },
        {
          'idDrink': 20,
          'strDrink': '50/50',
          'strDrinkAlternate': null,
          'strTags': null,
          'strCategory': 'Ordinary Drink',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': 'fill glass with crushed ice. Add vodka. Add a splash of grand-marnier. Fill with o.j.',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wwpyvr1461919316.jpg',
          'strIngredient1': 'Vanilla vodka',
          'strIngredient2': 'Grand Marnier',
          'strIngredient3': 'Orange juice',
          'strIngredient4': null,
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '2 1/2 oz ',
          'strMeasure2': '1 splash ',
          'strMeasure3': 'Fill with ',
          'strMeasure4': null,
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2016-04-29 09:41:56'
        },
        {
          'idDrink': 21,
          'strDrink': 'Zorro',
          'strDrinkAlternate': null,
          'strTags': null,
          'strCategory': 'Coffee / Tea',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': 'add all and pour black coffee and add whipped cream on top.',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/kvvd4z1485621283.jpg',
          'strIngredient1': 'Sambuca',
          'strIngredient2': 'Baileys irish cream',
          'strIngredient3': 'White Creme de Menthe',
          'strIngredient4': null,
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '2 cl ',
          'strMeasure2': '2 cl ',
          'strMeasure3': '2 cl ',
          'strMeasure4': null,
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2017-01-28 16:34:43'
        },
        {
          'idDrink': 22,
          'strDrink': 'Bijou',
          'strDrinkAlternate': null,
          'strTags': null,
          'strCategory': 'Cocktail',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': 'Stir in mixing glass with ice and strain\r\n',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rysb3r1513706985.jpg',
          'strIngredient1': 'Orange Bitters',
          'strIngredient2': 'Green Chartreuse',
          'strIngredient3': 'Gin',
          'strIngredient4': 'Sweet Vermouth',
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '1 dash',
          'strMeasure2': '1 oz',
          'strMeasure3': '1 oz',
          'strMeasure4': '1 oz',
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2017-12-19 18:09:45'
        },
        {
          'idDrink': 23,
          'strDrink': 'Affair',
          'strDrinkAlternate': null,
          'strTags': null,
          'strCategory': 'Ordinary Drink',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': 'Pour schnapps, orange juice, and cranberry juice over ice in a highball glass. Top with club soda and serve.',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/h5za6y1582477994.jpg',
          'strIngredient1': 'Strawberry schnapps',
          'strIngredient2': 'Orange juice',
          'strIngredient3': 'Cranberry juice',
          'strIngredient4': 'Club soda',
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '2 oz ',
          'strMeasure2': '2 oz ',
          'strMeasure3': '2 oz ',
          'strMeasure4': null,
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2016-09-01 10:05:34'
        },
        {
          'idDrink': 24,
          'strDrink': 'Boxcar',
          'strDrinkAlternate': null,
          'strTags': null,
          'strCategory': 'Ordinary Drink',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': 'In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a sour glass.',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/pwgtpa1504366376.jpg',
          'strIngredient1': 'Gin',
          'strIngredient2': 'Triple sec',
          'strIngredient3': 'Lemon juice',
          'strIngredient4': 'Grenadine',
          'strIngredient5': 'Egg white',
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '1 1/2 oz ',
          'strMeasure2': '1 oz ',
          'strMeasure3': '1 tsp ',
          'strMeasure4': '1/2 tsp ',
          'strMeasure5': '1 ',
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2017-09-02 16:32:57'
        },
        {
          'idDrink': 25,
          'strDrink': 'Orgasm',
          'strDrinkAlternate': null,
          'strTags': null,
          'strCategory': 'Ordinary Drink',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': 'Shake all ingredients with ice, strain into a chilled cocktail glass, and serve.',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vr6kle1504886114.jpg',
          'strIngredient1': 'Creme de Cacao',
          'strIngredient2': 'Amaretto',
          'strIngredient3': 'Triple sec',
          'strIngredient4': 'Vodka',
          'strIngredient5': 'Light cream',
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '1/2 oz white ',
          'strMeasure2': '1/2 oz ',
          'strMeasure3': '1/2 oz ',
          'strMeasure4': '1/2 oz ',
          'strMeasure5': '1 oz ',
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2017-09-08 16:55:14'
        },
        {     
          'idDrink': 26,
          'strDrink': 'Absolut Evergreen',
          'strDrinkAlternate': null,
          'strTags': null,
          'strCategory': 'Other / Unknown',
          'strAlcoholic': 'Alcoholic',
          'strInstructions': '',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wrxrxp1472812609.jpg',
          'strIngredient1': 'Gin',
          'strIngredient2': 'Grand Marnier',
          'strIngredient3': 'Lemon Juice',
          'strIngredient4': null,
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '1 3/4 shot ',
          'strMeasure2': '1 Shot ',
          'strMeasure3': '1/4 Shot',
          'strMeasure4': null,
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2017-09-07 21:42:09'
        },
        {     
          'idDrink': 27,
          'strDrink': 'Banana Milk Shake',         
          'strDrinkAlternate': null,
          'strTags': null,
          'strCategory': 'Shake',
          'strAlcoholic': 'Non alcoholic',
          'strInstructions': '',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rtwwsx1472720307.jpg',
          'strIngredient1': 'Banana',
          'strIngredient2': 'Milk',
          'strIngredient3': 'Ice Cream',
          'strIngredient4': null,
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '1 piece',
          'strMeasure2': '1/4 Shot ',
          'strMeasure3': '1 Shot',
          'strMeasure4': null,
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2017-09-07 21:42:09'
        },
        {     
          'idDrink': 28,
          'strDrink': 'Chocolate Monkey',      
          'strDrinkAlternate': null,
          'strTags': null,
          'strCategory': 'Cocoa',
          'strAlcoholic': 'Non Alcoholic',
          'strInstructions': '',
          'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/tyvpxt1468875212.jpg',
          'strIngredient1': 'Chocolate',
          'strIngredient2': 'Milk',
          'strIngredient3': null,
          'strIngredient4': null,
          'strIngredient5': null,
          'strIngredient6': null,
          'strIngredient7': null,
          'strIngredient8': null,
          'strIngredient9': null,
          'strIngredient10': null,
          'strIngredient11': null,
          'strIngredient12': null,
          'strIngredient13': null,
          'strIngredient14': null,
          'strIngredient15': null,
          'strMeasure1': '2 part',
          'strMeasure2': '1 Shot ',
          'strMeasure3': null,
          'strMeasure4': null,
          'strMeasure5': null,
          'strMeasure6': null,
          'strMeasure7': null,
          'strMeasure8': null,
          'strMeasure9': null,
          'strMeasure10': null,
          'strMeasure11': null,
          'strMeasure12': null,
          'strMeasure13': null,
          'strMeasure14': null,
          'strMeasure15': null,
          'dateModified': '2017-09-07 21:42:09'
        },
      ],
      {},
    );
  },

  down: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkDelete('drinks', {});
  },
};
